name: Run tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install gems
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl \
             --header "Content-type: application/json" \
             --header "Accept: application/vnd.github.antiope-preview+json" \
             --header "Authorization": "Bearer ${GITHUB_TOKEN}" \
             --data '{ "name":"Coverage", "head_sha":"${GITHUB_SHA}", "status":"in_progress" }' \
             "https://api.github.com/repos/nunesmatheus/metabase-data-api/check-runs"
