name: Run tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-bundle

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.1'

    - name: Build application
      run: |
        sudo gem install bundler
        bundle config set deployment 'true'
        bundle install
        rspec

    - name: Coverage action
      uses: nunesmatheus/check-runs-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        title: Test coverage
        output-message: 92% de coverage
        conclusion: failure
        summary: Low coverage value
